language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs-v1.0.3"
  - "iojs-v1.1.0"
  - "iojs-v1.2.0"
service:
  - mysql
  - memcached
before_script:
  - mysql -e 'create database myapp_test;'
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage 
